import { PlantFamilyColors } from '../Theme';

export const plantFamilyData = [
  {
    id: 'plantfamily-01',
    formal: 'Amaryllidaceae',
    common: 'Allium',
    color: PlantFamilyColors.allium,
    bg: 'pf-allium',
    examples: 'onion, garlic, leek, shallot',
  },
  {
    id: 'plantfamily-02',
    formal: 'Brassicaceae',
    common: 'Mustard',
    color: PlantFamilyColors.mustard,
    bg: 'pf-mustard',
    examples: 'broccoli, brussels sprout, cabbage, cauliflower, kale, arugula, turnip, pak choi, radish',
  },
  {
    id: 'plantfamily-03',
    formal: 'Chenopodioideae',
    common: 'Beetroot',
    color: PlantFamilyColors.beetroot,
    bg: 'pf-beetroot',
    examples: 'chard, spinach, beet',
  },
  {
    id: 'plantfamily-04',
    formal: 'Cucurbitaceae',
    common: 'Gourd',
    color: PlantFamilyColors.gourd,
    bg: 'pf-gourd',
    examples: 'squash, zucchini, cucumber, melon, cantaloupe, pumpkin',
  },
  {
    id: 'plantfamily-05',
    formal: 'Fabaaceae',
    common: 'Legume',
    color: PlantFamilyColors.legume,
    bg: 'pf-legume',
    examples: 'bean, pea',
  },
  {
    id: 'plantfamily-06',
    formal: 'Liliaceae',
    common: 'Lily',
    color: PlantFamilyColors.lily,
    bg: 'pf-lily',
    examples: 'asparagus',
  },
  {
    id: 'plantfamily-07',
    formal: 'Solanaceae',
    common: 'Nightshade',
    color: PlantFamilyColors.nightshade,
    bg: 'pf-nightshade',
    examples: 'tomato, potato, eggplant, pepper',
  },
  {
    id: 'plantfamily-08',
    formal: 'Umbelliferae',
    common: 'Umbell',
    color: PlantFamilyColors.umbell,
    bg: 'pf-umbell',
    examples: 'carrot, celeriac, cilantro, fennel, parsley, dill, parsnip',
  },
  {
    id: 'plantfamily-09',
    formal: 'Asteraceae',
    common: 'Daisy',
    color: PlantFamilyColors.daisy,
    bg: 'pf-daisy',
    examples: 'lettuce',
  },
  {
    id: 'plantfamily-10',
    formal: 'Other (Lamiaceae)',
    common: 'Mint',
    color: PlantFamilyColors.misc,
    bg: 'pf-misc',
    examples: 'basil,',
  },
];
