/* Raw data regarding seeds. */

// What is the difference, if any, between a "seed" and a "plant"?

export const seedData = [
  {
    id: 'seed-01',
    name: 'Asparagus',
    cultivar: 'Asparagus',
    variety: 'Purple Passion',
    vendor: 'Johnnys',
    vendorURL: 'https://www.johnnyseeds.com/vegetables/asparagus/purple-passion-f1-asparagus-crowns-2225.html',
    description: 'Sweeter and more tender than green varieties, and a colorful option for raw eating in salads. Color fades when cooked, but excellent flavor is retained.',
  },
  {
    id: 'seed-02',
    name: 'Broccoli',
    cultivar: 'Broccoli',
    variety: 'Solstice',
    vendor: 'Uprising Organics',
    vendorURL: 'https://uprisingorganics.com/collections/broccoli-rapini/products/broccoli-solstice',
    description: 'Big Vigorous plants hold their tight, dark green heads high above the leaves on very long stems with excellent side shoot production.',
  },
  {
    id: 'seed-03',
    name: 'Carrot',
    cultivar: 'Carrot',
    variety: 'Scarlet Nantes',
    vendor: 'Uprising Organics',
    vendorURL: 'https://uprisingorganics.com/collections/carrot/products/carrot-scarlet-nantes',
    description: 'Our open-pollinated scarlet nantes have plenty of the sweetness but also a rich real carrot flavor. Widely adapted, it is very versatile for everything from fresh baby carrots to fall storage and juicing. ',
  },
  {
    id: 'seed-04',
    name: 'Lettuce',
    cultivar: 'Lettuce',
    variety: 'Blue Rock',
    vendor: 'Johnnys',
    vendorURL: 'https://www.johnnyseeds.com/vegetables/lettuce/romaine-lettuce-cos/blue-rock-organic-lettuce-seed-4618G.html?cgid=romaine-lettuce#start=1',
    description: 'Attractive, dark green savoy leaves on tall, upright heads that fill out nicely and remain partially open when mature. ',
  },
  {
    id: 'seed-05',
    name: 'Kale',
    cultivar: 'Kale',
    variety: 'Dwarf Blue',
    vendor: 'Seed Savers',
    vendorURL: 'https://www.seedsavers.org/dwarf-blue-curled-organic-kale',
    description: 'Gorgeous finely curled blue-green leaves hold their color even in severe cold.',
  },
  {
    id: 'seed-06',
    name: 'Leek',
    cultivar: 'Leek',
    variety: 'PrizeTaker',
    vendor: 'Seed Savers',
    vendorURL: 'https://www.seedsavers.org/prizetaker-leek',
    description: 'Very hardy 36" tall plants with thick, solid, pure-white base. ',
  },
  {
    id: 'seed-07',
    name: 'Radish',
    cultivar: 'Radish',
    variety: 'China Rose',
    vendor: 'Baker Creek',
    vendorURL: 'https://www.rareseeds.com/store/vegetables/radishes/china-rose-radish',
    description: 'One of the oldest types of radish. A very hardy fall/winter variety. Roots are about 5” long and a rose color.',
  },
  {
    id: 'seed-08',
    name: 'Sugar Pea',
    cultivar: 'Sugar Pea',
    variety: 'Oregon Giant',
    vendor: 'Resilient Seeds',
    vendorURL: 'https://www.resilientseeds.com/store/p146/Sugar_Pea_-_Oregon_Giant_%28Certified_Organic%29.html',
    description: 'Highly recommended by Carol Deppe in “The Tao of Vegetable Gardening”, this edible-pod pea has huge pods and big crinkled seeds.',
  },
  {
    id: 'seed-09',
    name: 'Tomato',
    cultivar: 'Tomato',
    variety: 'Orange King',
    vendor: 'Resilient Seeds',
    vendorURL: 'https://www.resilientseeds.com/store/p129/Tomato_-_Orange_King_%28Certified_Organic%29.html',
    description: 'Early, productive, and worth growing even as a sprawling, low-maintenance outdoor tomato in the cool Pacific Northwest. ',
  },
  {
    id: 'seed-10',
    name: 'Chard',
    cultivar: 'Chard',
    variety: 'Rainbow',
    vendor: 'Resilient Seeds',
    vendorURL: 'https://www.resilientseeds.com/store/p124/Chard%2C_Rainbow_%28Certified_Organic%29.html',
    description: 'A farmers market favorite, rainbow chard is a mix of green, red, orange, and yellow leaf types that make an attractive combination in salads or bunched on display. ',
  },
];
