name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run ESLint
        run: npm run lint
      - name: Publish github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/agilegardenclub/public-garden-45ght3cf.git
          CI=false npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
