name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build NPM package
        run: npm run build
      - name: Publish github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/agilegardenclub/public-garden-45ght3cf.git
          npm run gh-pages -- -d build -u "github-actions-bot <support+actions@github.com>"
